idade = int
nome = str
cpf = float
dataDeNascimento = str
peso = float
cidade = str
estado = str
velocidade = float
preco = float

idade = 19
nome = "José Arcangelo"
cpf = "049.001.020-24"
dataDeNascimento = "29/09/2003"
peso = 66
cidade = "Nova Palma"
estado = "RS"
velocidade = 80
preco = 7.50
